### ISSUE TITLE
[편지함] 편지함 목록

### ISSUE THREAD

**Issue by yoouyeon** [weeklyJisimi/jinsim-front#14]
## ✨ 작업 설명

- /letter-box (작업자가 알아서... 멋진 url 만들어주길)
- 편지함에 저장된 편지 목록 페이지

## 🛠️ 작업 내용

- [x] #37
- [ ] 보관 가능 편지 데이터 보여주기
- [x] 편지 정렬 (제목, 만든날짜 순)
- [x] To 목록
- [x] To 필터링
- [x] 편지 상세 페이지로 이동

## 📝 참고

```
[편지함 - To 목록 받아오기]

[편지함 - 목록 받아오기]
요청 (쿼리)
정렬 (제목, 만든 날짜 순)
To

응답
제목
편지지 이미지
보관 가능 편지 개수

```

**Comment by hyeon81** [comment]
![image](https://github.com/user-attachments/assets/271cb57a-ed24-474b-b12b-a4d434b65882)
실수로 메인에 merge 해버림..
